In [1]:
import pandas as pd
from pathlib import Path

In [ ]:
beneficiaries.csv
customers.csv
customer_behavior.csv
customer_beneficiaries.csv
customer_devices.csv
devices.csv
merchants.csv
sanction_list.csv
transactions.csv
transaction_analysis_logs.csv

In [ ]:
# Data folder path
DATA_DIR = Path("Data/CSV_Files")

# Load datasets
beneficiaries = pd.read_csv(DATA_DIR / "beneficiaries.csv")
customers = pd.read_csv(DATA_DIR / "customers.csv")
customer_behavior = pd.read_csv(DATA_DIR / "customer_behavior.csv")
customer_beneficiaries = pd.read_csv(DATA_DIR / "customer_beneficiaries.csv")
customer_devices = pd.read_csv(DATA_DIR / "customer_devices.csv")
devices = pd.read_csv(DATA_DIR / "devices.csv")
merchants = pd.read_csv(DATA_DIR / "merchants.csv")
sanction_list = pd.read_csv(DATA_DIR / "sanction_list.csv")
transactions = pd.read_csv(DATA_DIR / "transactions.csv")
transaction_analysis_logs = pd.read_csv(DATA_DIR / "transaction_analysis_logs.csv")

:

In [32]:
audit_logs.head()

,audit_id,transaction_id,customer_id,fraud_probability,behavior_score,graph_score,sanction_score,overall_risk_score,risk_category,decision,...,behavior_agent_output,graph_agent_output,risk_agent_output,explainability_output,shap_top_features,recommended_action,linked_fraud_cases,report_path,investigation_status,created_at
0,AUD00000000,TXN00000000,CUST11860,22.0,9.05,9.42,0.0,22.0,LOW,APPROVED,...,Behavioral Agent: Input dynamics show transact...,Graph Agent: Evaluated structural path pattern...,Risk Orchestration Agent: Aggregated core beha...,Explainability Summary: Transaction evaluation...,"{""device_risk_weight"": 0.07, ""graph_connection...",PASS,NaN,/reports/pdf/TXN00000000_forensic_summary.pdf,CLOSED,2026-04-07 13:18:00
1,AUD00000001,TXN00000001,CUST10233,92.0,88.57,87.89,0.0,92.0,HIGH,BLOCKED,...,Behavioral Agent: Input dynamics show transact...,Graph Agent: Evaluated structural path pattern...,Risk Orchestration Agent: Aggregated core beha...,Explainability Summary: Transaction evaluation...,"{""velocity_24h_delta"": 0.79, ""graph_connection...",IMMEDIATE_SAR_FILING,CASE187,/reports/pdf/TXN00000001_forensic_summary.pdf,OPEN,2026-03-11 09:56:00
2,AUD00000002,TXN00000002,CUST10109,92.0,87.30,85.17,0.0,92.0,HIGH,BLOCKED,...,Behavioral Agent: Input dynamics show transact...,Graph Agent: Evaluated structural path pattern...,Risk Orchestration Agent: Aggregated core beha...,Explainability Summary: Transaction evaluation...,"{""graph_connection_degree"": 0.75, ""velocity_24...",IMMEDIATE_SAR_FILING,CASE96,/reports/pdf/TXN00000002_forensic_summary.pdf,OPEN,2026-05-14 23:23:00
3,AUD00000003,TXN00000003,CUST10963,83.0,78.18,28.26,0.0,83.0,HIGH,BLOCKED,...,Behavioral Agent: Input dynamics show transact...,Graph Agent: Evaluated structural path pattern...,Risk Orchestration Agent: Aggregated core beha...,Explainability Summary: Transaction evaluation...,"{""velocity_24h_delta"": 0.78, ""device_risk_weig...",IMMEDIATE_SAR_FILING,CASE15,/reports/pdf/TXN00000003_forensic_summary.pdf,OPEN,2026-04-11 11:09:00
4,AUD00000004,TXN00000004,CUST11020,22.0,5.17,18.84,0.0,22.0,LOW,APPROVED,...,Behavioral Agent: Input dynamics show transact...,Graph Agent: Evaluated structural path pattern...,Risk Orchestration Agent: Aggregated core beha...,Explainability Summary: Transaction evaluation...,"{""graph_connection_degree"": 0.1, ""device_risk_...",PASS,NaN,/reports/pdf/TXN00000004_forensic_summary.pdf,CLOSED,2026-05-31 11:41:00

In [26]:
transactions.columns

Index(['transaction_id', 'customer_id', 'receiver_account', 'merchant_id',
       'transaction_timestamp', 'transaction_type', 'transaction_amount',
       'currency', 'payment_method', 'transaction_status', 'device_id',
       'ip_address', 'origin_country', 'destination_country',
       'is_international', 'transaction_frequency_24h',
       'avg_transaction_amount_7d', 'failed_transaction_count_24h',
       'unusual_amount_flag', 'unusual_location_flag',
       'multiple_transactions_short_time', 'high_risk_device_flag',
       'velocity_flag', 'fraud_flag', 'fraud_risk', 'created_at'],
      dtype='object')

In [31]:
transactions.head()

,transaction_id,customer_id,receiver_account,merchant_id,transaction_timestamp,transaction_type,transaction_amount,currency,payment_method,transaction_status,...,avg_transaction_amount_7d,failed_transaction_count_24h,unusual_amount_flag,unusual_location_flag,multiple_transactions_short_time,high_risk_device_flag,velocity_flag,fraud_flag,fraud_risk,created_at
0,TXN00000000,CUST11860,ACC8760139014,MER0053,2026-04-07 13:18:00,TRANSFER,1449.97,INR,ONLINE,SUCCESS,...,1334.35,0,False,False,False,False,False,False,LOW,2026-04-07 13:18:00
1,TXN00000001,CUST10233,ACC8657075548,MER0059,2026-03-11 09:56:00,WIRE,9684.04,INR,ONLINE,DECLINED,...,7869.86,7,False,True,True,True,True,True,HIGH,2026-03-11 09:56:00
2,TXN00000002,CUST10109,ACC3780475472,MER0097,2026-05-14 23:23:00,CARD,18227.65,INR,ONLINE,DECLINED,...,19275.03,6,False,True,True,True,True,True,HIGH,2026-05-14 23:23:00
3,TXN00000003,CUST10963,ACC3869961166,MER0045,2026-04-11 11:09:00,TRANSFER,12060.11,INR,ONLINE,DECLINED,...,12410.48,5,False,True,True,False,True,True,HIGH,2026-04-11 11:09:00
4,TXN00000004,CUST11020,ACC9447304615,MER0034,2026-05-31 11:41:00,WIRE,785.07,INR,ONLINE,SUCCESS,...,823.45,1,False,False,False,False,False,False,LOW,2026-05-31 11:41:00

In [25]:
transactions[:1]["transaction_amount"].values[0]

np.float64(1449.97)

In [33]:
audit_logs[:1]["behavior_agent_output"].values[0]

'Behavioral Agent: Input dynamics show transaction speed variance. Interaction cadence signature matches automated bot behaviors: False.'

In [11]:
list(transactions.columns)

['transaction_id',
 'customer_id',
 'receiver_account',
 'merchant_id',
 'transaction_timestamp',
 'transaction_type',
 'transaction_amount',
 'currency',
 'payment_method',
 'transaction_status',
 'device_id',
 'ip_address',
 'origin_country',
 'destination_country',
 'is_international',
 'transaction_frequency_24h',
 'avg_transaction_amount_7d',
 'failed_transaction_count_24h',
 'unusual_amount_flag',
 'unusual_location_flag',
 'multiple_transactions_short_time',
 'high_risk_device_flag',
 'velocity_flag',
 'fraud_flag',
 'fraud_risk',
 'created_at']

In [2]:
from IPython.display import IFrame

IFrame("https://www.google.com", width=1000, height=600)